### ISSUE TITLE
Поддержка нескольких аудио дорожек

### ISSUE THREAD

**Issue by apalchys** [TroRg/plex.kino.pub#2]
Как я понял, kino.pub API поддерживает выбор аудио дорожки в режиме hls.  Предлагаю сделать такую же возможность в плагине. Например, генерировать MediaObject для каждой уникальной пары video+audio, т.е. если есть 3 качества видео и 3 аудио дорожки, то получим 9 MediaObject. 

В данный момент фильмы можно смотреть только с аудио дорожкой которая идет первой и это не всегда та, которая нужна.

**Comment by TroRg** [comment]
Такой вариант давно рассматривается, незнаю когда введем. А пока просто переключайте тип стриминга на HTTP для выбора дорожек.

**Comment by apalchys** [comment]
@TroRg "А пока просто переключайте тип стриминга на HTTP для выбора дорожек."
А точно ли такой вариант доступен в плагине данный момент? На Xbox и Samsung SmartTV всегда только одна дорожка, если даже на сайте их несколько.

**Comment by ArStudio** [comment]
Видимо, все зависит от возможностей клиента. В плеере Apple TV4 есть возможность менять дорожки.

**Comment by TroRg** [comment]
Совершенно верно, все зависит от клиента. Веб клиент например сможет отдавать аудио только через HLS с указанными трэками в MediaContainer(чего пока нет).
